/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package supermarket;

import javax.swing.JOptionPane;
import model.Kebutuhan;
import model.Makanan;
import model.Minuman;
import model.Product;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

import model.Product;
import model.Makanan;
import model.Minuman;
import model.Kebutuhan;
import model.ProductDAO;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


/**
 *
 * @author timi
 */
public class PanelTambahProduk extends javax.swing.JPanel {
            DefaultTableModel model;

            private model.ProductDAO dao;
            public PanelTambahProduk() {
            initComponents();

        try {
            dao = new ProductDAO();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error inisialisasi ProductDAO: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        hargaTxt = new javax.swing.JTextField();
        stockTxt = new javax.swing.JTextField();
        categoryCbx = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0, 80));

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel2.setText("Nama Product");

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel5.setText("Stock");

        namaTxt.setBackground(new java.awt.Color(255, 255, 225));

        hargaTxt.setBackground(new java.awt.Color(255, 255, 225));

        stockTxt.setBackground(new java.awt.Color(255, 255, 225));

        categoryCbx.setBackground(new java.awt.Color(255, 255, 225));
        categoryCbx.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        categoryCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Kebutuhan" }));

        jLabel6.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel6.setText("Tambah Produk");

        addBtn.setBackground(new java.awt.Color(255, 255, 225));
        addBtn.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(namaTxt)
                    .addComponent(hargaTxt)
                    .addComponent(stockTxt)
                    .addComponent(categoryCbx, 0, 311, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaTxt)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );

        add(jPanel1);
        jPanel1.setBounds(30, 70, 690, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\timi\\OneDrive\\design project.png")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-3, -4, 1080, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        addBtn.addActionListener(new ActionListener() {
            
    @Override
    public void actionPerformed(ActionEvent e) {
        String nama = namaTxt.getText().trim();
        String kategori = categoryCbx.getSelectedItem().toString();
        double harga;
        int stok;

        try {
            harga = Double.parseDouble(hargaTxt.getText().trim());
            stok = Integer.parseInt(stockTxt.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Harga dan stok harus berupa angka.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama produk tidak boleh kosong.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buat objek produk
        Product produk;
        int idDummy = 0; // ID akan di-generate otomatis di database

        switch (kategori) {
            case "Makanan":
                produk = new Makanan(idDummy, nama, harga, stok);
                break;
            case "Minuman":
                produk = new Minuman(idDummy, nama, harga, stok);
                break;
            case "Kebutuhan":
                produk = new Kebutuhan(idDummy, nama, harga, stok);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Kategori tidak dikenali.", "Kategori Error", JOptionPane.ERROR_MESSAGE);
                return;
        }

        // Simpan ke database
        try {
            ProductDAO dao = new ProductDAO();
            dao.insertProduct(produk);
            JOptionPane.showMessageDialog(null, "Produk berhasil ditambahkan ke database!");

            // Reset input form
            namaTxt.setText("");
            hargaTxt.setText("");
            stockTxt.setText("");
            categoryCbx.setSelectedIndex(0);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal menambahkan produk ke database.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
});

    }//GEN-LAST:event_addBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> categoryCbx;
    private javax.swing.JTextField hargaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField stockTxt;
    // End of variables declaration//GEN-END:variables
}
