/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package supermarket;
import javax.swing.table.DefaultTableModel;
import model.Cart; // Pastikan Cart terimport
import model.CartItem; // Pastikan CartItem terimport
import model.Product; // Pastikan Product terimport
import model.ProductDAO; // Pastikan ProductDAO terimport
import javax.swing.JOptionPane; // Pastikan JOptionPane terimport
        
/**
 *
 * @author timi
 */
public class PanelKeranjang extends javax.swing.JPanel {

  private DefaultTableModel tableModel; // Gunakan ini sebagai model utama untuk tabelKeranjang
//   private javax.swing.JLabel totalLabel; // <-
  
  private Cart currentCart;
    
  public PanelKeranjang() { // <-- PASTIKAN HANYA KONSTRUKTOR INI YANG ADA (jika memilih opsi A)
        initComponents();
        tableModel = new DefaultTableModel(new String[]{"ID Produk", "Nama Produk", "Kategori", "Jumlah", "Harga Satuan", "Subtotal"}, 0);
        tabelKeranjang.setModel(tableModel);
        tableModel.setRowCount(0);
//        totalLabel = totalLbl;
        // currentCart belum diinisialisasi di sini, akan diinisialisasi via setCart()
    }

    public void setCart(Cart cart) { // <-- PASTIKAN METODE INI ADA
        this.currentCart = cart;
        updateFromCart(this.currentCart);
    }
    
//    public void setCart(Cart cart) {
//        this.currentCart = cart;
//        updateFromCart(this.currentCart); // Perbarui tampilan saat keranjang diatur
//    }

    
    
     public void updateFromCart(Cart cart) {
       tableModel.setRowCount(0);
        double grandTotal = 0.0;
        if (cart != null) { // <--- PENTING: Cek apakah Cart tidak null sebelum menggunakannya
            for (CartItem item : cart.getItems()) {
                String kategoriProduk = "";
                if (item.getProduct() != null) {
                    kategoriProduk = item.getProduct().getKategori();
                }
                tableModel.addRow(new Object[]{
                    item.getProduct().getId(),
                    item.getProduct().getNama(),
                    kategoriProduk,
                    item.getQuantity(),
                    item.getProduct().getHarga(),
                    item.getSubtotal()
                });
                grandTotal += item.getSubtotal();
            }
        }
        if (totalLbl != null) { // <--- GUNAKAN totalLbl, BUKAN totalHargaLabel atau totalLabel
            totalLbl.setText(String.format("Rp. %.2f", grandTotal));
        }
    }

    // Hapus metode redundant ini: updateTabelKeranjang(), tampilkanKeranjang()
    // karena updateFromCart(Cart cart) sudah cukup dan lebih baik.
    // public void updateTabelKeranjang() { ... }
    // public void tampilkanKeranjang() { ... }

//     public void updateTabelKeranjang() {
//    keranjangModel.setRowCount(0); // clear dulu
//    
//    for (CartItem item : keranjang) {
//    keranjangModel.addRow(new Object[]{
//            item.getProductId(),
//            item.getNama(),
//            item.getKategori(),
//            item.getHarga(),
//            item.getStock(),
//            item.getTotalHarga()
//        });
//    }
//  }
     
//     public void tampilkanKeranjang() {
//    DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama", "Kategori", "Quantity", "Harga"}, 0);
//    
//    double total = 0;
//    for (CartItem item : MainDashboardUser.keranjang) {
//        model.addRow(new Object[]{
//            item.id,
//            item.nama,
//            item.kategori,
//            item.quantity,
//            item.harga
//        });
//        total += item.quantity * item.harga;
//    }
//
//    tabelKeranjang.setModel(model);
//    totalLabel.setText("Rp. " + total);
//}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        bayarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kembalianLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        printBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelKeranjang);

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel2.setText("KERANJANG ");

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        bayarBtn.setText("BAYAR");
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("TOTAL:");

        totalLbl.setText("Rp.");

        jLabel5.setText("TUNAI");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setText("KEMBALIAN:");

        kembalianLbl.setText("Rp. ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        printBtn.setText("PRINT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(317, 317, 317))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kembalianLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addComponent(bayarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(totalLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(kembalianLbl))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bayarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(printBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
     
    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        // TODO add your handling code here
    try {
            double totalHarga = 0.0;
            if (totalLbl != null && !totalLbl.getText().isEmpty()) { // <--- Pastikan pakai totalLbl
                String totalText = totalLbl.getText().replace("Rp. ", "").replace(",", "");
                totalHarga = Double.parseDouble(totalText);
            }

            double jumlahBayar = Double.parseDouble(jTextField1.getText());

            if (jumlahBayar < totalHarga) {
                JOptionPane.showMessageDialog(this, "Jumlah bayar kurang dari total harga!", "Pembayaran Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double kembalian = jumlahBayar - totalHarga;
            kembalianLbl.setText(String.format("Rp. %.2f", kembalian));

            JOptionPane.showMessageDialog(this, "Pembayaran berhasil!\nKembalian Anda: " + String.format("Rp. %.2f", kembalian));

            // --- HIDUPKAN KODE INI DAN PASTIKAN METODE ADA DI ProductDAO DAN Cart ---
            if (currentCart != null) { // <--- Pastikan currentCart tidak null
                ProductDAO productDAO = new ProductDAO(); // Buat instance DAO di sini
                for (CartItem item : currentCart.getItems()) {
                    // Pastikan ProductDAO memiliki metode kurangiStock(int productId, int quantity)
                    productDAO.kurangiStock(item.getProduct().getId(), item.getQuantity()); //
                }
                currentCart.clearCart(); // Kosongkan keranjang setelah transaksi
                updateFromCart(currentCart); // Perbarui tampilan tabel keranjang
                totalLbl.setText("Rp. 0.00"); // Reset total
            } else {
                JOptionPane.showMessageDialog(this, "Error: Objek keranjang tidak tersedia.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            // --- AKHIR KODE YANG DIHIDUPKAN ---

            jTextField1.setText("");
            kembalianLbl.setText("Rp. ");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah tunai yang valid.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat proses pembayaran: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_bayarBtnActionPerformed


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
      int selectedRow = tabelKeranjang.getSelectedRow();
    if (selectedRow != -1) {
        int productIdToDelete = (int) tableModel.getValueAt(selectedRow, 0);
            // Asumsi ada metode removeItem(productId) di kelas Cart Anda
            currentCart.removeItem(productIdToDelete);
            updateFromCart(currentCart); // Perbarui tampilan tabel setelah menghapus item
            JOptionPane.showMessageDialog(this, "Produk berhasil dihapus dari keranjang.");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kembalianLbl;
    private javax.swing.JButton printBtn;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
