
package supermarket;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


import model.Product;
import model.Makanan;
import model.Minuman;
import model.Kebutuhan;
import model.ProductDAO;
import model.TransactionDAO;
import model.Cart;
import model.CartItem;
        

/**
 *
 * @author timi
 */
public class UserPanel extends javax.swing.JPanel {
    List<CartItem> keranjang = new ArrayList<>();
    DefaultTableModel keranjangModel;
    DefaultTableModel productModel;
    DefaultTableModel tableModel;
//    private DefaultTableModel tableModel; //
//   private javax.swing.JLabel totalLabel; // <-
  
  private Cart currentCart;

    public UserPanel() {
        initComponents();
//        this.setLocationRelativeTo(null);
        qtySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1)); // default: 1, min: 1, max: 100, step: 1
        
        tableModel = new DefaultTableModel(new String[]{"ID", "Nama", "Kategori", "Harga", "Stock"}, 0);
        tabelProduk.setModel(tableModel);
        keranjangModel = new DefaultTableModel(new String[] {
        "ID", "Nama", "Kategori", "Harga", "Qty", "Total"
        }, 0);
        tabelKeranjang.setModel(keranjangModel);
        loadTableProduk(); 

    tabelProduk.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent evt) {
        int baris = tabelProduk.getSelectedRow();
        if (baris != -1) {
            idTxt.setText(tabelProduk.getValueAt(baris, 0).toString());
            nameTxt.setText(tabelProduk.getValueAt(baris, 1).toString());
            categoryTxt.setText(tabelProduk.getValueAt(baris, 2).toString());
            hargaTxt.setText(tabelProduk.getValueAt(baris, 3).toString());

        }
}
});
}

         private void loadTableProduk() {
    try {
        ProductDAO dao = new ProductDAO();
        List<Product> produkList = dao.getAllProducts();
        DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/aft mart", "root", "");
//// Atau yang lebih disarankan untuk development:
//        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/aft mart?autoReconnect=true&useSSL=false", "root", "");
        String sql = "SELECT * FROM products";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet resultSet = stmt.executeQuery();  // ✅ INI WAJIB ADA


//        while (resultSet.next()) {
//            int stock = resultSet.getInt("stock"); // Ambil dari database
//            Object[] row = {id, nama, kategori, harga, stock};
//            tableModel.addRow(row);
//        }
        

        model.setRowCount(0);
        for (Product p : produkList) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNama(),
                p.getKategori(),
                p.getHarga(),
                p.getStock()
            });
            
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal ambil data produk: " + e.getMessage());
    }
}

    
//    public void updateTabelKeranjang() {
//        tabelKeranjang.(0); // clear dulu
//        for (CartItem item : keranjang) {
//        tabelKeranjang.addRow(new Object[]{
//                item.getProductId(),
//                item.getNama(),
//                item.getKategori(),
//                item.getHarga(),
//                item.getStock(),
//                item.getTotalHarga()
//            });
//        }
//      }
     public void updateTabelKeranjang() {
        DefaultTableModel model = (DefaultTableModel) tabelKeranjang.getModel();
        model.setRowCount(0); // clear tabel sebelum diisi ulang

        for (CartItem item : keranjang) {
            model.addRow(new Object[]{
                item.getProduct().getId(),
                item.getProduct().getNama(),
                item.getProduct().getKategori(),
                item.getProduct().getHarga(),
                item.getProduct().getStock(),
                item.getTotalHarga()
            });
        }
    }




        


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        categoryTxt = new javax.swing.JTextField();
        hargaTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        qtySpinner = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        bayarBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        totalLbl = new javax.swing.JLabel();
        kembalianLbl = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 0, 80));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Harga", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tabelProduk);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU ITEMS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        hargaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTxtActionPerformed(evt);
            }
        });

        tambahBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tambahBtn.setText("TAMBAH KERANJANG");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Quantity");

        qtySpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtySpinnerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(37, 37, 37))
                                    .addComponent(jLabel5))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(20, 20, 20)))
                            .addComponent(jLabel4))
                        .addGap(371, 371, 371))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hargaTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(categoryTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tambahBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(categoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(idTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahBtn)
                .addGap(174, 174, 174))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 0, 80));

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Harga"
            }
        ));
        jScrollPane2.setViewportView(tabelKeranjang);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("KERANJANG");

        bayarBtn.setText("BAYAR");
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        printBtn.setText("PRINT");

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("TUNAI");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("KEMBALIAN");

        totalLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        totalLbl.setText("Rp. ");

        kembalianLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kembalianLbl.setText("Rp.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kembalianLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteBtn)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bayarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(printBtn)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3))
                    .addComponent(totalLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kembalianLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void hargaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTxtActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
    try {
        int id = Integer.parseInt(idTxt.getText());
        String nama = nameTxt.getText();
        String kategori = categoryTxt.getText(); // atau ambil dari combo box
        double harga = Double.parseDouble(hargaTxt.getText());
        int qty = (int) qtySpinner.getValue();
        int selectedRow = tabelProduk.getSelectedRow();
        int stock = Integer.parseInt(tabelProduk.getValueAt(selectedRow, 4).toString()); // kolom ke-4 = stock
        Product produk = new Makanan(id, nama, harga, stock); // contoh kalau kategori makanan
        
    if (qty > produk.getStock()) {
    JOptionPane.showMessageDialog(this, "Stock tidak mencukupi.");
    return;
}



switch (kategori.toLowerCase()) {
    case "makanan":
        produk = new Makanan(id, nama, harga, stock);
        break;
    case "minuman":
        produk = new Minuman(id, nama, harga, stock);
        break;
    case "kebutuhan":
        produk = new Kebutuhan(id, nama, harga, stock);
        break;
    default:
        JOptionPane.showMessageDialog(this, "Kategori tidak dikenali.");
        return;
}

    CartItem item = new CartItem(produk, qty);
    keranjang.add(item);
    updateTabelKeranjang();


    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Gagal tambah ke keranjang: " + ex.getMessage());
    }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
 try {
            double totalHarga = 0.0;
            if (totalLbl != null && !totalLbl.getText().isEmpty()) { // <--- Pastikan pakai totalLbl
                String totalText = totalLbl.getText().replace("Rp. ", "").replace(",", "");
                totalHarga = Double.parseDouble(totalText);
            }

            double jumlahBayar = Double.parseDouble(jTextField1.getText());

            if (jumlahBayar < totalHarga) {
                JOptionPane.showMessageDialog(this, "Jumlah bayar kurang dari total harga!", "Pembayaran Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double kembalian = jumlahBayar - totalHarga;
            kembalianLbl.setText(String.format("Rp. %.2f", kembalian));

            JOptionPane.showMessageDialog(this, "Pembayaran berhasil!\nKembalian Anda: " + String.format("Rp. %.2f", kembalian));

            // --- HIDUPKAN KODE INI DAN PASTIKAN METODE ADA DI ProductDAO DAN Cart ---
            if (currentCart != null) { // <--- Pastikan currentCart tidak null
                ProductDAO productDAO = new ProductDAO(); // Buat instance DAO di sini
                for (CartItem item : currentCart.getItems()) {
                    // Pastikan ProductDAO memiliki metode kurangiStock(int productId, int quantity)
                    productDAO.kurangiStock(item.getProduct().getId(), item.getQuantity()); //
                }
                currentCart.clearCart(); // Kosongkan keranjang setelah transaksi
                updateFromCart(currentCart); // Perbarui tampilan tabel keranjang
                totalLbl.setText("Rp. 0.00"); // Reset total
            } else {
                JOptionPane.showMessageDialog(this, "Error: Objek keranjang tidak tersedia.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            // --- AKHIR KODE YANG DIHIDUPKAN ---

            jTextField1.setText("");
            kembalianLbl.setText("Rp. ");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah tunai yang valid.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat proses pembayaran: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_bayarBtnActionPerformed

    private void qtySpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtySpinnerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_qtySpinnerMouseClicked


    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
      int selectedRow = tabelKeranjang.getSelectedRow();
    if (selectedRow != -1) {
        int productIdToDelete = (int) tabelKeranjang.getValueAt(selectedRow, 0); // ambil ID produk dari kolom ke-0

        // cari dan hapus item dari list keranjang
        for (int i = 0; i < keranjang.size(); i++) {
            if (keranjang.get(i).getProduct().getId() == productIdToDelete) {
                keranjang.remove(i);
                break;
            }
        }

        updateTabelKeranjang(); // refresh isi tabel
        JOptionPane.showMessageDialog(this, "Produk berhasil dihapus dari keranjang.");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    
    
       
    /**
     * @param args the command line arguments
     */
 
public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> {
        new UserPanel().setVisible(true);
});
}

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarBtn;
    private javax.swing.JTextField categoryTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField hargaTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel kembalianLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton printBtn;
    private javax.swing.JSpinner qtySpinner;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
